twittergram/config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  devise_for :users
  
  resources :posts do
    resources :comments
  end

  resources :bios
end

twittergram/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

twittergram/app/models/bio.rb
class Bio < ApplicationRecord
  belongs_to :user
end

twittergram/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

twittergram/app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
end

twittergram/app/models/user.rb
class User < ApplicationRecord
  has_one :bio, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

twittergram/app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

twittergram/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

twittergram/app/controllers/bios_controller.rb
class BiosController < ApplicationController
  before_action :set_bio, only: [:show, :update, :edit, :destroy]
  before_action :set_user, only: [:create]
  
  def index
    @bios = Bio.all
  end

  def show
  end

  def new
    @bio = Bio.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @user.bio = Bio.new(bio_params)
    if @user.bio.save
      redirect_to bios_path
    else
      render partial: "form"
    end
  end


  def update
    if @bio.update(bio_params)
      redirect_to bios_path(current_user)
    else
      render partial: "form"
    end
  end

  def destroy
    @bio.destroy
    redirect_to bio_path
  end

  private

    def set_bio
      @bio = Bio.find(params[:id])
    end

    def bio_params
      params.require(:bio).permit(:profile_image, :description, :user_id)
    end

    def set_user
      @user = current_user
    end
end

twittergram/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def index
    @comments = @post.comments
  end

  def show
  end

  def new
    @comment = @post.comments.new
    render partial: 'form'
  end

  def edit
    render partial: 'form'
  end

  def create
    @comment = @post.comments.new(comment_params)

    if @comment.save
      redirect_to [@post, @comment]
    else
      render partial: 'form'
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to [@post, @comment]
    else
      render partial: 'form'
    end
  end

  def destroy
    @comment.destory
    redirect_to post_comments_path(@post)

  end

  private

    def set_post
      @post = Post.find(params[:post_id])
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:message, :user_id, :post_id)
end

twittergram/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :update, :edit, :destroy]
  def index
    @posts = current_user.posts
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      flash[:success] = "Posted Successfully!"
      redirect_to root_path
    else
      flash[:alert] = "Failed to post"
      render partial: "form"
    end
  end


  def update
    if @post.update(post_params)
      flash[:success] = "Updated Post Successfully!"
      redirect_to root_path
    else
      flash[:alert] = "Failed to update post!"
      render partial: "form"
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Post deleted!"
    redirect_to posts_path
  end

  private

    def set_post
      @post = current_user.posts.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:content, :user_id)
    end
end

twittergram/app/helpers/accounts_helper.rb
module AccountsHelper
end

twittergram/app/helpers/application_helper.rb
module ApplicationHelper
end

twittergram/app/helpers/bios_helper.rb
module BiosHelper
end

twittergram/app/helpers/comments_helper.rb
module CommentsHelper
end

twittergram/app/helpers/posts_helper.rb
module PostsHelper
end

twittergram/app/helpers/users_helper.rb
module UsersHelper
end

twittergram/app/views/accounts/edit.html.erb
<h1>Accounts#edit</h1>
<p>Find me in app/views/accounts/edit.html.erb</p>

twittergram/app/views/accounts/index.html.erb
<h1>Accounts#index</h1>
<p>Find me in app/views/accounts/index.html.erb</p>

twittergram/app/views/accounts/new.html.erb
<h1>Accounts#new</h1>
<p>Find me in app/views/accounts/new.html.erb</p>

twittergram/app/views/accounts/show.html.erb
<h1>Accounts#show</h1>
<p>Find me in app/views/accounts/show.html.erb</p>

twittergram/app/views/bios/_form.html.erb
<%= form_for @bio do |f| %>
  <h1>Tell us about yourself...</h1>
  <%= f.text_field :description, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

twittergram/app/views/bios/edit.html.erb
<h1>Bios#edit</h1>
<p>Find me in app/views/bios/edit.html.erb</p>

twittergram/app/views/bios/index.html.erb
<div class="ui four column centered grid">
  <div class="column">
    <ul >
      <div class="row">
        <li class="ui list"> 
          <div class="ui card" style="width: 285px">
            <div class="content">
              <div class="header"><%= current_user.email%></div>
              <div class="description">
                <div class="header">
                <h3>About Me...</h3>
                </div>
                <h4><%= current_user.bio.description %></h4>
              </div>
            </div>
            <div class="extra content">
              <%= link_to '<i class="write icon"></i>'.html_safe, edit_bio_path(current_user.bio)%> 
              <%= link_to '<i class="trash icon"></i>'.html_safe, @bio, method: :delete %> 
            </div>
          </div>
        </li>
      </div>
    </ul>
  </div>
</div>

twittergram/app/views/bios/show.html.erb
<h1>Bios#show</h1>
<p>Find me in app/views/bios/show.html.erb</p>

twittergram/app/views/comments/_form.html.erb
<h1>Add a comment</h1>
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :message %>
  <%= f.text_area :message, required: true %>
  <br />
 <%= f.submit %>
<% end %>

twittergram/app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

twittergram/app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

twittergram/app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

twittergram/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twittergram</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render(partial: 'shared/navbar') %>
      <%= render(partial: 'shared/flash') %>
    <div>
      <%= yield %>
    </div>
  </body>
</html>

twittergram/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <h1>Whats Happening?</h1>
  <%= f.text_field :content, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

twittergram/app/views/posts/edit.html.erb
<div class="page_title_button">
<h1>
<%= render 'form', post: @post %>
</div>

twittergram/app/views/posts/index.html.erb
<%= link_to 'Profile', bios_path(current_user), class: "item" %>
<h2 class="ui center aligned icon header">
  <i class="circular users icon"></i>
  TweetGram Feed
</h2>
<div class="ui four column centered grid">
  <div class="column">
    <ul >
      <% @posts.reverse.each do |post| %>
      <div class="row">
        <li class="ui list"> 
          <div class="ui card" style="width: 285px">
            <div class="content">
              <div class="header"><%= post.user.email %></div>
              <div class="description">
                <%= link_to post.content, post %>
              </div>
            </div>
            <div class="extra content">
              <span class="left floated">
                <i class="calendar icon"></i>
                <%= post.created_at.strftime("%m/%d/%Y at %I:%M %p") %>
              </span>
              <span class="right floated">
                <%= link_to '<i class="write icon"></i>'.html_safe, edit_post_path(post)%> 
                <%= link_to '<i class="trash icon"></i>'.html_safe, post, method: :delete %> 
              </span>
            </div>
          </div>
        </li>
        <br>
        </div>
      <% end %>
    </ul>
  </div>
</div>

twittergram/app/views/posts/new.html.erb
<div class="page_title_button">
<%= render 'form', post: @post %>
</div>

twittergram/app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

twittergram/app/views/shared/_flash.html.erb
<div class="ui container">
  <% flash.each do |key, value| %>
    <% if key == "success" %>
      <div class="ui compact positive large message">
    <% elsif key == "alert" %>
      <div class="ui compact negative large message">
    <% else %>
      <div class="ui compact large message ">
    <% end %>
      <i class="close icon"></i>
        <p><%= value %></p>
    </div>
  <% end %> 
</div>

twittergram/app/views/shared/_navbar.html.erb
<div class="ui inverted segment">
  <div class="ui inverted secondary pointing menu">
    <a class="item">
      <%= link_to "Home", root_path, class: "item" %>
    </a>
    <a class="item">
      <%= link_to "Post", new_post_path, class: "item" %>
    </a>
    <div class="right menu">
    <a class="item">
      
    </a>
    <a class="item">
      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "item" %>
    </a>
    </div>
  </div>
</div>
      

twittergram/app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

twittergram/app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

twittergram/app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>